### ISSUE TITLE
Home Assistant integration/card similar to singlyricly

### ISSUE THREAD

**Issue by NicoLeOca** [kalkih/singlyricly#22]
Hi!
I am a happy user of your mini-media-card and I was passing by when I saw Singlyricly
I am looking for something similar for HA to have lyrics dynamically displayed in a card next to mini-media-card.
This:
https://github.com/robert-alfaro/genius-lyrics
does part of the job without the automatic scrolling.
I intend to display everything to my TV, showing what's played on my Sonos.

Would you be interested in building an integration for HA?

Anyway, thanks for building mini-media-card.

**Comment by kalkih** [comment]
Hello,

Fun idea, unfortunately Spotify changed the usage policy for their API, and this app is no longer allowed to use it.
Coincidence that Spotify just recently released the synced lyrics feature throughout their apps? 😉    

Anyways, rhe reasons this app is no longer allowed:
* The product or service is integrated with streams or content from another service.
* Synchronization: Spotify content is used in the background of visual media, such as advertising, film, TV programs, livestreams, slideshow videos (etc.)

Singlyricly is very basic and doesn't use any external services for content, the only content that could be considered "content from another service" are the Lyrics, which are sourced in SInglyricly itself by its users.

**Comment by NicoLeOca** [comment]
Hi,

Thanks for letting me know 
Sorry for your app.
That's a shame Spotify changed their policy.
Even if their integration is nice, it doesn't cover every usage.

So my only hope is an integration which takes the lyrics from one service and get it synced somehow using the spotify integration in HA.

**Comment by NicoLeOca** [comment]
Hello,

Another idea would be to have lyrics displayed scrolling in mini-media-card in place of the full-cover. 
No need of Spotify I imagine
What do you think?
